version: "3.2"
services:
  nodejs:
    build:
      context: .
    image: tthandb/task-management
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-service
      - MYSQL_USER=binhnd
      - MYSQL_PASS=123
      - MYSQL_DB=task-management
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: nodejs-service
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=binhnd
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=task-management
    container_name: mysql-service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-service
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-service
networks:
  frontend:
  backend:
