version: "3.2"
services:
  nodejs:
    build:
      context: .
    image: tthandb/task-management
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=task-management
      - MYSQL_USER=binhnd
      - MYSQL_PASS=123456
      - MYSQL_DB=task-management
    volumes:
        - ./www/:/var/www/html/
    ports:
        - "2000:2000"
    container_name: nodejs-service
  mysql:
    image: mysql:8
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=binhnd
      - MYSQL_PASS=123456
      - MYSQL_DATABASE=task-management
    container_name: mysql-service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "2001:80"
    environment:
      - PMA_HOST= mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-service
networks:
  frontend:
  backend:
